# config/packages/doctrine.yaml
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        dbname:               nubehive_CredLoans
        host:                 127.0.0.1
        port:                 33060
        user:                 '%env(resolve:DATABASE_USER)%'
        password:             '%env(resolve:DATABASE_PASSWORD)%'
        driver:               pdo_mysql
        # if the url option is specified, it will override the above config
        #url:                  mysql://db_user:db_password@127.0.0.1:3306/db_name
        # the DBAL driverClass option
        #driver_class:         App\DBAL\MyDatabaseDriver
        # the DBAL driverOptions option
        options:
          foo: bar
        path:                 '%kernel.project_dir%/var/data/data.sqlite'
        memory:               true
        unix_socket:          /tmp/mysql.sock
        # the DBAL wrapperClass option
        #wrapper_class:        App\DBAL\MyConnectionWrapper
        charset:              utf8mb4
        logging:              '%kernel.debug%'
        #platform_service:     App\DBAL\MyDatabasePlatformService #'8.0.39'
        server_version:       '10.0.0'
        mapping_types:
          enum: string
        #types:
        #  custom: App\DBAL\MyCustomType

  orm:
    entity_managers:
      default:
        mappings:
          App:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
