controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
productsDirectory:
    path: /products-directory/product/{productDirectoryId}
    methods: GET|HEAD
    controller: App\Controller\ProductDirectoryController::index